---

- name: Copy backend dist files to remote server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Install Node modules
  shell: |
    cd home/ubuntu/backend
    npm install

- name: Build Node App
  shell: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: Start the App with PM2
  shell: pm2 start npm -- run "start:dev"
  args:
    chdir: /home/ubuntu/backend

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls