---

- name: Copy backend dist files to remote server
  synchronize:
    src: /root/project/backend/
    dest: /home/ubuntu/backend

- name: Install Node modules
  shell: npm install
  args:
    chdir: /home/ubuntu/backend

- name: Build Node App
  shell: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: Start the App with PM2
  shell: pm2 start npm -- run "start:dev"
  args:
    chdir: /home/ubuntu/backend

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls